/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


void GenerateException(void);

int Multiply (int a, int b, int c)
{
	return a * b * c;
}



#define RAM_END                 (0x20000000U + (128*1024))
#define MSP_END                 (RAM_END)
#define MSP_START_PSP_END       (RAM_END - 512)
#define PSP_START               (RAM_END - 1024)

int main(void)
{


	__asm volatile(".equ RAM_END, (0x20000000U + (128*1024)) ");
	__asm volatile(".equ MSP_START_PSP_END, (RAM_END - 512) ");

	/* initialize psp with valid sp */
	__asm volatile ("LDR R0, = MSP_START_PSP_END");
	__asm volatile ("MSR PSP, R0");

	/* Link SP to PSP */
	__asm volatile ("LDR R0, =#0x02");
	__asm volatile ("MSR CONTROL, R0");

	int res;
	res = Multiply(4, 5, 6);

	GenerateException();





    /* Loop forever */
	for(;;);
}




void GenerateException(void)
{
	/* Supervisor call (SVC)*/
	__asm volatile("SVC #0x2");
}

void SVC_Handler(void)
{
   /*  */
}
